# fly.toml app configuration file generated for imageuploaderapp on 2023-07-14T23:42:52-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "imageuploaderapp"
primary_region = "eze"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
